from __future__ import annotations

class Colorize:
    def reset(self) -> Colorize: ...
    def bold(self) -> Colorize: ...
    def dim(self) -> Colorize: ...
    def italic(self) -> Colorize: ...
    def underline(self) -> Colorize: ...
    def blink(self) -> Colorize: ...
    def inverse(self) -> Colorize: ...
    def hidden(self) -> Colorize: ...
    def strikethrough(self) -> Colorize: ...

    def black(self) -> Colorize: ...
    def red(self) -> Colorize: ...
    def green(self) -> Colorize: ...
    def yellow(self) -> Colorize: ...
    def blue(self) -> Colorize: ...
    def magenta(self) -> Colorize: ...
    def cyan(self) -> Colorize: ...
    def white(self) -> Colorize: ...
    def color256(self, color: int, /) -> Colorize: ...
    def custom(self, red: int, green: int, blue: int) -> Colorize: ...
    def default(self) -> Colorize: ...

    def on_black(self) -> Colorize: ...
    def on_red(self) -> Colorize: ...
    def on_green(self) -> Colorize: ...
    def on_yellow(self) -> Colorize: ...
    def on_blue(self) -> Colorize: ...
    def on_magenta(self) -> Colorize: ...
    def on_cyan(self) -> Colorize: ...
    def on_white(self) -> Colorize: ...
    def on_color256(self, color: int, /) -> Colorize: ...
    def on_custom(self, red: int, green: int, blue: int) -> Colorize: ...
    def on_default(self) -> Colorize: ...
